### ISSUE TITLE
Range status spreadsheet link is broken

### ISSUE THREAD

**Issue by gonidelis** [cplusplus/SG9#3]
Any idea why:
https://github.com/cplusplus/SG9/blame/main/Info.md#L34

leads to:

"**Sorry, the file you have requested has been deleted.**"?

**Comment by inbal2l** [comment]
The link should be working fine. Please double-check on your side.

**Comment by gonidelis** [comment]
Maybe it's not open for public access? I do not have any special permissions.

**Comment by gonidelis** [comment]
Any updates on this one?

**Comment by inbal2l** [comment]
Hello @gonidelis ,
As mentioned, this problem was not reproduced by other users.
Please send me an email to: sinbal2lextra@gmail.com
I'll send you a direct link and an offline version of the document. Thanks!

Closing the issue.
